### ISSUE TITLE
"fdupes not found" on macOS when started from GUI

### ISSUE THREAD

**Issue by mivk** [mx1up/fdupes-gui#1]
On macOS, when trying to start `fdupes-gui` by double-clicking `/Applications/fdupes_gui.app` in the Finder, the window only shows

    fdupes not found

and it cannot be used.

But it works if it is started from the Terminal as

    /Applications/fdupes_gui.app/Contents/MacOS/fdupes_gui

I thought it might be because `fdupes` is in a path only defined in `~/.zshrc`, but it seems the system-wide path is correct.

```
√ ~ % which fdupes
/usr/local/bin/fdupes

√ ~ % cat /etc/paths # ( and same content in /private/etc/paths )
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```
This is on macOS Big Sur 11.17.10.

My workaround for now was to add an alias in `~/.zshrc` (or `~/.bash_profile` if you use Bash) :

    alias fdupes-gui=/Applications/fdupes_gui.app/Contents/MacOS/fdupes_gui

and start it from Terminal with `fdupes-gui`.

Anyway, thanks a lot for this, which is very nice to have for people who are not familiar with the command-line.

**Comment by mx1up** [comment]
hi @mivk 

thanks for the feedback. The reason is that the terminal and the gui have different environments. In the gui environment `/usr/local/bin` is not part of your path. 

I will add a button to locate the `fdupes` binary manually.

**Comment by mivk** [comment]
Yes, that is what I suspected initially. But as you can see, `/usr/local/bin/` is in the global `/etc/paths`. 

Where else could a path be set? I had asked Google before posting this, but didn't find anywhere else in what I read (except an a old mention of an environtment.plist file, which doesn't seem to exist on this system).

But if there is indeed no way in current macOS systems to specify a global path, then your solution would be a good one.

**Comment by mx1up** [comment]
I don't think `/etc/paths` applies to the gui environment, see for example this [SO comment](https://serverfault.com/questions/16355/how-do-i-set-the-global-path-environment-variable-on-os-x#comment578920_146142).

Anyway, I added the custom location button. Please try out this test version:
[fdupes_gui.zip](https://github.com/user-attachments/files/17176891/fdupes_gui.zip)

and let me know whether it works :)

**Comment by mx1up** [comment]
updated test version:
[fdupes_gui.zip](https://github.com/user-attachments/files/17179410/fdupes_gui.zip)

mainly b2833dd879e41789862c73449769d6ec8e8dcff6

**Comment by mivk** [comment]
Thank you! Indeed it works after giving the custom location. (sorry for taking so long to respond. I only got access now to this machine which is not mine).
